# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.BigIntegerField(unique=True)),
                ('is_new', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='unique_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
